# Generated by Django 6.0.6 on 2026-07-07 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_duration', models.IntegerField(default=0)),
                ('shift_date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('duration_hours', models.IntegerField()),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('flat_rate', 'Flat Rate')], default='hourly', max_length=50)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professional_type', models.CharField(choices=[('RN', 'Registered Nurse (RN)'), ('LPN', 'Licensed Practical Nurse'), ('CP', 'Certified Phlebotomist')], default='CP', max_length=100)),
                ('job_type', models.CharField(choices=[('urgent', 'Urgent'), ('full_day', 'Full Day'), ('part_time', 'Part Time')], default='full_day', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_duration', models.IntegerField(default=0)),
                ('shift_date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('flat_rate', 'Flat Rate')], default='hourly', max_length=50)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professional_type', models.CharField(choices=[('RN', 'Registered Nurse (RN)'), ('LPN', 'Licensed Practical Nurse'), ('CP', 'Certified Phlebotomist')], default='CP', max_length=100)),
                ('job_type', models.CharField(choices=[('urgent', 'Urgent'), ('full_day', 'Full Day'), ('part_time', 'Part Time')], default='full_day', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_url', models.TextField(blank=True, null=True)),
                ('signed_by_phlebotomist', models.BooleanField(default=False)),
                ('signed_by_client', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='pending', max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='jobs.job')),
                ('phlebotomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('phlebotomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'phlebotomist')},
            },
        ),
    ]
