# Generated by Django 6.0.6 on 2026-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_job_id_alter_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_certifications',
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('full_day', 'Full Day'), ('part_time', 'Part Time')], default='full_day', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('flat_rate', 'Flat Rate')], default='hourly', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='professional_type',
            field=models.CharField(choices=[('RN', 'Registered Nurse (RN)'), ('LPN', 'Licensed Practical Nurse'), ('CP', 'Certified Phlebotomist')], default='CP', max_length=100),
        ),
    ]
