# Generated by Django 6.0.6 on 2026-07-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_job_id_alter_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='jobtemplate',
            name='duration_hours',
        ),
    ]
