# Generated by Django 6.0.6 on 2026-07-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_duration_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtemplate',
            name='status',
        ),
    ]
