# Generated by Django 6.0.6 on 2026-07-09 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_payment_options_and_more'),
        ('jobs', '0004_remove_jobtemplate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='appointments.appointment'),
        ),
    ]
