# Generated by Django 6.0.6 on 2026-07-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_shift_duration_jobassignment_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_duration', models.IntegerField(default=0)),
                ('shift_date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('duration_hours', models.IntegerField()),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('flat_rate', 'Flat Rate')], default='hourly', max_length=50)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professional_type', models.CharField(choices=[('RN', 'Registered Nurse (RN)'), ('LPN', 'Licensed Practical Nurse'), ('CP', 'Certified Phlebotomist')], default='CP', max_length=100)),
                ('job_type', models.CharField(choices=[('urgent', 'Urgent'), ('full_day', 'Full Day'), ('part_time', 'Part Time')], default='full_day', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
