# Generated by Django 6.0.6 on 2026-07-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobassignment',
            old_name='signed_by_provider',
            new_name='signed_by_client',
        ),
        migrations.RemoveField(
            model_name='jobassignment',
            name='provider',
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
