# Generated by Django 6.0.6 on 2026-07-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobassignment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='jobassignment',
            name='start_time',
        ),
    ]
