# Generated by Django 6.0.6 on 2026-07-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Primepath Service Agreement', max_length=255)),
                ('last_updated', models.CharField(default='January 2025', max_length=100)),
                ('is_legally_binding', models.BooleanField(default=True)),
                ('terms_of_service_text', models.TextField(default='By using Phlebotomist services, you agree to provide accurate healthcare services in accordance with professional standards and applicable regulations. This agreement establishes the framework for our partnership.')),
                ('terms_of_service_points', models.JSONField(default=list, help_text='List of key points for terms of service')),
                ('payment_policies_text', models.TextField(default='Payment terms are Net 15 days from service completion. Direct deposit is our preferred payment method, with payments processed bi-weekly.')),
                ('payment_policies_callout', models.CharField(default='Average processing time: 2-3 business days', max_length=255)),
                ('legal_disclaimers_text', models.TextField(default='This agreement is governed by state healthcare regulations. Both parties acknowledge understanding of their rights and responsibilities under this partnership.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
