# Generated by Django 6.0.6 on 2026-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsofservice',
            name='is_legally_binding',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='legal_disclaimers_text',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='payment_policies_callout',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='payment_policies_text',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='terms_of_service_points',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='terms_of_service_text',
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
