# Generated by Django 6.0.6 on 2026-07-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('inappropriate_language', 'Inappropriate Language'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('fake_profile', 'Fake Profile'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
