# Generated by Django 6.0.6 on 2026-07-06 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phlebotomist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('license_expiry_date', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('specialty', models.CharField(choices=[('general_phlebotomy', 'General Phlebotomy'), ('iv_insertion_or_therapy', 'IV Insertion/Therapy'), ('oncology_or_chemotherapy', 'Oncology/Chemotherapy'), ('medical_nurse', 'Medical Nurse')], max_length=100)),
                ('work_preference', models.CharField(choices=[('part_time', 'Part-time'), ('full_time', 'Full-time')], max_length=100)),
                ('service_area', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phlebotomist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phlebotomist_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='phlebotomist_documents/')),
                ('approved', models.BooleanField(default=False)),
                ('phlebotomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='authentication.phlebotomist')),
            ],
            options={
                'unique_together': {('phlebotomist', 'document_name', 'approved')},
            },
        ),
        migrations.CreateModel(
            name='Phlebotomist_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('phlebotomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='authentication.phlebotomist')),
            ],
            options={
                'unique_together': {('phlebotomist', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='PhlebotomistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('phlebotomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='authentication.phlebotomist')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('phlebotomist', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
