# Generated by Django 6.0.6 on 2026-07-06 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_phlebotomist_phlebotomist_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phlebotomist',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('healthcare', 'Healthcare'), ('individual', 'Individual')], max_length=255)),
                ('business_address_street', models.CharField(max_length=255)),
                ('business_address_city', models.CharField(max_length=255)),
                ('business_address_state', models.CharField(max_length=255)),
                ('business_address_zip', models.CharField(max_length=10)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_license_number', models.CharField(max_length=100)),
                ('business_description', models.TextField()),
                ('hourly_pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_job_type', models.CharField(choices=[('in_clinic_phlebotomy', 'In-Clinic Phlebotomy'), ('mobile_blood_draw', 'Mobile Blood Draw'), ('laboratory_testing', 'Laboratory Testing')], max_length=100)),
                ('work_preference', models.CharField(choices=[('part_time', 'Part-time'), ('full_time', 'Full-time')], max_length=100)),
                ('no_of_employees', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='client_documents/')),
                ('approved', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='authentication.client')),
            ],
            options={
                'unique_together': {('client', 'document_name', 'approved')},
            },
        ),
        migrations.CreateModel(
            name='ClientWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='authentication.client')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('client', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
