# Generated by Django 6.0.6 on 2026-07-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_phlebotomist_years_of_experience_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='client',
        ),
    ]
