# Generated by Django 6.0.6 on 2026-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_user_client_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='client_signatures/'),
        ),
    ]
