# Generated by Django 6.0.6 on 2026-07-07 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_client_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phlebotomist_document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phlebotomist_document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document_name',
            field=models.CharField(choices=[('license', 'License'), ('signature', 'signature')], max_length=100),
        ),
        migrations.AlterField(
            model_name='phlebotomist_document',
            name='document_name',
            field=models.CharField(choices=[('license', 'License'), ('identification', 'Identification')], max_length=100),
        ),
    ]
