# Generated by Django 6.0.6 on 2026-07-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_clientdocument_created_at_clientdocument_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_approved',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='phlebotomist',
            name='approved',
            field=models.BooleanField(default=None),
        ),
    ]
