# Generated by Django 6.0.6 on 2026-07-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_client_is_approved_alter_phlebotomist_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='phlebotomist',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='phlebotomist_document',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
