# Generated by Django 6.0.6 on 2026-07-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_client_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
