# Generated by Django 6.0.6 on 2026-07-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_clientdocument_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
