# Generated by Django 6.0.6 on 2026-07-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
    ]
