# Generated by Django 6.0.6 on 2026-07-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_add_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_job_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_preference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phlebotomist',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
    ]
