# Generated by Django 6.0.6 on 2026-07-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phlebotomist',
        ),
    ]
